# Permalinks
permalink:           pretty

# Setup
title:               Symphony
tagline:             'Data Acquisition System'
description:         'Symphony is a MATLAB based data acquisition system for electrophysiologists.'
url:                 http://symphony-das.github.io
baseurl:             ''
usergroup:           https://groups.google.com/forum/#!forum/symphony-das

# About/contact
author:
  name:              Symphony-DAS
  url:               http://symphony-das.github.io
  email:             symphony-das@googlegroups.com

# Custom vars
version:             2.5.3.4

github:
  repo:              https://github.com/Symphony-DAS/symphony-matlab
  org:               https://github.com/Symphony-DAS

gitbook:
  book:              https://cafarm.gitbooks.io/symphony
